{% set name = "shapemapper2" %}
{% set version = "2.1.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Sargueil-CiTCoM/shapemapper2 
  git_depth: 1

build:
  number: 1
  script: 
    - "cmake && make"
    - "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
    # - "{{ PYTHON }} setup.py install" # --single-version-externally-managed --record=record.txt || exit 1; "
  
requirements:
  host:
    - python
    - pip
    - gcc 
    - setuptools
  run:
    - python
    - setuptools
    - cython
    - scipy=1.9.*
    - numpy=1.23.*
    - scikit-learn=1.*
    - bbmap=37.*
    - java-jdk=8.*
    - bowtie2
    - varna
    - graphviz
    - star=2.5.2a
    - ruamel_yaml
    - matplotlib=1.5.*
    - perl-threaded
    - ghostscript
    - pv



about:
  home: https://github.com/Sargueil-CiTCoM/shapemapper2 
  license: GPL3
  license_family: GPL3
  summary: 
